-- Demo seed data intentionally contains no accounts, passwords, phone numbers,
-- tokens, or other personal data. Create the first administrator through the
-- protected provisioning workflow (or an explicit local-only SQL seed).
--
-- Production deployments must not use shared default credentials.
